spring.application.name=restaurant-api

# where the database is running.
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant

# username and password provide credentials for the database connection
spring.datasource.username=postgres
spring.datasource.password=manager

# determines how the schema is created, updated or validated.
spring.jpa.hibernate.ddl-auto=validate

# show the SQL statements in the console for debugging purposes.
spring.jpa.show-sql=true

# specify the Hibernate dialect to use for PostgreSQL, which helps Hibernate
# generate the appropriate SQL syntax for the database.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# enable Flyway for database migrations and specify the location of migration scripts.
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Enable virtual threads for better performance in handling concurrent requests.
spring.threads.virtual.enabled=true

payment.api.url=http://localhost:9090